### ISSUE TITLE
user not allowed to modify/edit existing senses

### ISSUE THREAD

**Issue by lindsayferrara** [Signbank/Global-signbank#1032]
Hi (sorry, this is my first time on Github), I am a main administrator for the NTS dataset -- and I am unable to edit existing senses or add new senses to signs that already exist in Signbank or to new signs. I get an error message "sense update not allowed" after I write in/modify existing senses and push the update sense button. I am also not allowed to add new senses--even for new signs, after writing in a new sense and clicking on 'confirm add' I get an error that say "sense creation not allowed".
Can this be fixed? Thank you, Lindsay Ferrara

**Comment by susanodd** [comment]
We will check your permissions. The coders and @ocrasborn all have superuser permission. Probably something was omitted.

**Comment by Jetske** [comment]
@lindsayferrara we just added more rights to edit senses, so it should be working if you try again :)

**Comment by lindsayferrara** [comment]
Hi, thanks for all of your quick responses! It seems I can now edit existing senses. I still cannot add new senses-- either to existing signs or if I create a new sign. All users with 'change' access in the NTS dataset will need these permissions--because they will be adding new signs as we annotate the corpus. I do not see where I can grant this permission--I can only add or remove people with 'change' access.
Again, thanks for your help on this :)

**Comment by susanodd** [comment]
The users need to be in group Editor in order to have the sense permissions. Plus have the permissions to change the dataset (as you have done).

**Comment by susanodd** [comment]
I modified the Dataset Manager page so that acronyms are used in the URLs and get parameters to the commands available to the user.
This way spaces in the dataset names (which contain spaces) are avoided.
I also removed the html element-id on the hidden dataset argument since these were not unique and contained spaces.
These modifications were done to avoid potential browser glitches because of the spaces.
(It varies per browser how lenient the browser is on parsing html.)

**Comment by susanodd** [comment]
@lindsayferrara we can't yet check what the permissions of the users with NTS dataset change permission are as the red and green check box icons are missing in the guardian installation, so it's not possible to confirm the user permissions yet. @Woseseltops will install the missing admin glyphs asap.

**Comment by susanodd** [comment]
@lindsayferrara I checked by hand the permissions in the admin for NTS.

All of the users who have change dataset permission for this dataset are also in group Editor.

They should all be able to work with senses.

**Comment by lindsayferrara** [comment]
Hello all, I can now edit senses. But I still cannot add new senses to 1) existing signs or 2) new signs. I simply am directed to a blank page that says "sense creation not allowed" (attached pic). 

![Skjermbilde 2023-08-30 kl  11 44 49](https://github.com/Signbank/Global-signbank/assets/141919647/00f3d3b9-8dec-4474-becf-83d95e67e809)

**Comment by susanodd** [comment]
@Woseseltops @vanlummelhuizen can you guys take a look at the error logs on the server to see what is happening?
It’s something with the new permissions for senses. Previously we merely tested for change gloss plus change dataset permissions.
The new permissions are in the permissions for group Editor but maybe some of the actual Python code or control flow messes with these? There are plenty of try-except statements, perhaps these cause the permissions to be ignored? Or some additional permissions have not been added to Editor.

**Comment by Jetske** [comment]
```
if not request.user.has_perm('dictionary.create_sense'):
        return HttpResponseForbidden("Sense Creation Not Allowed")
```
It must be here, so maybe the permission doesn't exist or it has not been added to the Editor group?

**Comment by vanlummelhuizen** [comment]
`dictionary.create_sense` does not exist. It should be `dictionary.add_sense`.

**Comment by susanodd** [comment]
This fix should be done on master.

**Comment by Jetske** [comment]
That makes sense. I changed it, but don't know how to test if that solves it.

**Comment by Jetske** [comment]
@lindsayferrara the changes are online now, can you try again?

**Comment by lindsayferrara** [comment]
Hi, YES! It works now. I tried it, and I also had another editor try--and we both could add senses now (to existing and new signs). Thank you. We cannot delete them, so maybe something to add later on? But for now, it means we can use Signbank again.

**Comment by Jetske** [comment]
Sorry, I seem to have accidentally deleted the delete button. It will be up again soon!

**Comment by Jetske** [comment]
@lindsayferrara it should be working again :)

**Comment by lindsayferrara** [comment]
Yup, the delete button is back and works. Thank you!!

**Comment by susanodd** [comment]
This seems to be working correctly.
