### ISSUE TITLE
Problems sending senses to api_update_gloss

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1360]
I am noticing a lot of errors regarding this gloss: 
 
While submitting request to update phonology I am getting error Database locked at HUREN-C. 

WHen submitting empty phonology feature such as: 

"Handshape Change": ""

The handshape change is still not modified to empty value.

**Comment by rem0g** [comment]
Ok, using "-" works! Thank you very much. 

About gloss HUREN-C; 

TransactionManagementError at /dictionary/api_update_gloss/5/49249/
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

This is what i have sent: 

{"Handedness": "N/A", "Strong Hand": "-", "Weak Hand": "B", "Handshape Change": "-", "Relation Between Articulators": "-", "Location": "-", "Contact Type": "-", "Movement Shape": "-", "Movement Direction": "-", "Repeated Movement": "", "Alternating Movement": "", "Relative Orientation: Movement": "-", "Relative Orientation: Location": "-", "Orientation Change": "-", "Virtual Object": "-", "Phonology Other": "-", "Mouth Gesture": "-", "Mouthing": "-", "Phonetic Variation": "-", "Senses": "{\"en\": [[\"hire\"], [\"rent, lease\"]], \"nl\": [[\"huren\"], [\"huren\"]]}"}

**Comment by rem0g** [comment]
Semantic Field and Phonology Other fields dont seem to be updated too.

**Comment by susanodd** [comment]
> Phonology Other fields dont seem to be updated too.
> 
> Modifing the values to the ones you mentioned didnt help, it is causing only by this gloss but it could happen at other glosses too.

Is this a newly created gloss, or an older gloss you are updating?

(If it's the latter there could be an old field inside the gloss from when the field choices used to be "character strings with machine value" instead of "object reference to FieldChoice.)

I will investigate the gloss itself.

Does your error message mention a specific line of code?

It's true that if it finds an error in the input fields, it will not do the update. (It's implemented as all or nothing, otherwise the transaction would be inconsistent.)

Do you want Handedness to be N/A ?
(Some of the query code excludes these from queries.)

**Comment by susanodd** [comment]
These fields:

"Virtual Object": "-", "Phonology Other": "-", "Mouth Gesture": "-", "Mouthing": "-", "Phonetic Variation": "-", 

are strings, so you can just put empty strings (the ones that are choices need to be "-")

If you don't want to set any value, you can exclude them from the json dictionary.
(It is ambiguous as to whether an empty value is a clear or to just ignore the field. So if you want to ignore the field and leave it as it is, don't include it in the update.)
I will check this again based on the logs.

**Comment by susanodd** [comment]
It looks like the gloss doesn't have any Phonology yet
Can you remove the fields from the update that stay "empty" from the update json fields?
So it only includes fields that need to be set.
Then make Handedness be 1 and set the Strong Hand not the Weak Hand.
As far as I know, if Handedness is 1, then the Strong Hand is set. (@uklomp can confirm this.)

**Comment by susanodd** [comment]
I can't find any errors related to the HUREN gloss. So the code thinks it's working correctly.
I  can merely see that you tried the update url numerous times. But it is not raising any errors in the log.
Farther back, I find this one:
```
Internal Server Error: /dictionary/api_update_gloss/5/49249/
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'at[pid: 283|app: 0|req: 5442/11576] 10.208.155.251 () {62 vars in 1118 bytes} [Wed Jul 24 16:56:02 2024] POST /dictionary/api_update_gloss/5/49249/ => generated 282396 bytes in 517 msecs (HTTP/1.1 500) 5 headers in 178 bytes (1 switches on core 3)
```
(That's all it reports, nothing about what specifically.)

In the logs, there is an error for ANTONI GAUDI

```
  File "/usr/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1342, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.12/http/client.py", line 1179, in putrequest
    self._output(self._encode_request(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1260, in _encode_request
    return request.encode('ascii')
           ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xcd' in position 15: ordinal not in range(128)

```

For the zip files, you don't need to put the gloss annotation in the zipped filename. It can be something else, like videos_archive.zip
It gets the annotation from inside the unzipped folder.

(I'm revising that code but it's not done yet.)

**Comment by rem0g** [comment]
There is definitely something wrong with HUREN-C, as i am trying to send this: 

{"Handedness": "1", "Strong Hand": "-", "Weak Hand": "-", "Handshape Change": "-", "Relation Between Articulators": "-", "Location": "-", "Contact Type": "-", "Movement Shape": "-", "Movement Direction": "-", "Repeated Movement": "False", "Alternating Movement": "False", "Relative Orientation: Movement": "-", "Relative Orientation: Location": "-", "Orientation Change": "-", "Virtual Object": "-", "Phonology Other": "-", "Mouth Gesture": "-", "Mouthing": "-", "Phonetic Variation": "-", "Senses": "{\"en\": [[\"hire\"], [\"rent, lease\"]], \"nl\": [[\"huren\"], [\"huren\"]]}"}


Interestingly, the update goes through when i send like this: 

{"Handedness": "1", "Strong Hand": "-", "Weak Hand": "-", "Handshape Change": "-", "Relation Between Articulators": "-", "Location": "-", "Contact Type": "-", "Movement Shape": "-", "Movement Direction": "-", "Repeated Movement": "False", "Alternating Movement": "False", "Relative Orientation: Movement": "-", "Relative Orientation: Location": "-", "Orientation Change": "-", "Virtual Object": "-", "Phonology Other": "-", "Mouth Gesture": "-", "Mouthing": "-", "Phonetic Variation": "-"}

So that's JSON payload without Senses. 

Something is going wrong with Senses field?

**Comment by susanodd** [comment]
I'll post here what it encounters for the senses (yes, it fails.
```

{'Senses': '{"en": [["hire"], ["rent, lease"]], "nl": [["huren"], ["huren"]]}'}
reorder_senses exception saving translation to other sense, removing offender
```
(It should not be doing anything with the senses because it is the same as the original field.)

**Comment by rem0g** [comment]
It works again! Thank you

**Comment by Jetske** [comment]
@rem0g One more thing relevant to this issue:
We noticed that you send all the fields in the request to update the gloss. However this gives a lot of non-informative changes in the revision history (see https://signbank.cls.ru.nl/dictionary/gloss/49249/history)

We clearly did not document this well ;) 
However the intention for this api was to only include the fields that are changed so it only updates those and leaves the others as is and they are not added to the revision history. Just so you know! You can close this issue again when read.

**Comment by susanodd** [comment]
The format is wrong that you show above.

**Comment by rem0g** [comment]
Can you please explain why is the format wrong? It's the format i got from the API documentation:

https://signbank.github.io/Global-signbank/#/Updating%20Signbank%20data/post_dictionary_api_update_gloss__datasetid___glossid__

With omitted strings as you mentioned before. 

About the empty requests, yes I will be soon working on that soon. :)

**Comment by susanodd** [comment]
I looks like you have return characters in it?

The processing needs to parse it, so it should be without pretty printing. (It's a Python library that parses it.)

Normally, "strip" is done to make sure there are no spaces in the input.

You you post your actual input value for the field? I will find out if there is a parsing error.

**Comment by Woseseltops** [comment]
Sure. I'll be working for the RU again this Thursday and Friday, let me know if you need it sooner

**Comment by susanodd** [comment]
We're missing @Jetske now.

**Comment by susanodd** [comment]
> This is what was sent:
> 
> {'Senses': {'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}}
> 
> I have tried different variations with slashes around en/nl and arrays, but nothing is working so far.
> 
> @Woseseltops I would be glad if you could fix this problem (OR explain in a clear way what formatting is expected with Senses) with alternative approach because this method is clearly not working for API purposes. :)

It looks like `['rent, lease']` has a comma inside of a quoted item?
I don't recall whether this is allowed? Did you try it as `['rent', 'lease']`

The two "language" lists need to be the same length (that is, one item per sense) but the keywords per sense can be a different length.

**Comment by Jetske** [comment]
{"Senses": "{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}}"

It's probably a dict, but in a string, such as above.

**Comment by rem0g** [comment]
@Woseseltops can you remove .strip() from 


`def get_gloss_update_human_readable_value_dict(request):
    post_data = json.loads(request.body)

    value_dict = dict()
    for field in post_data.keys():
        value = post_data.get(field, '')
        value_dict[field] = value.strip()
    return value_dict`
    

 Strip() is not required and can cause instability. Were there test units created for this function? I can't find that in the repo.

**Comment by susanodd** [comment]
All of the API fields are strings when they are passed.
Can you give an example of a value that this fails on?

The strip was intended to remove any characters at the end of strings. This is to weed out empty input fields. The same is done for the normal interface. The human readable value needs to be compared to the field choice values, for example.

**Comment by susanodd** [comment]
If you can tell me which field specifically it is complaining about the "strip" on, I shall revise the code. The human readable function should only be being called on the choice list fields. It needs to be there for example for something like a handshape "3 > O" to make sure there are no extra spaces on it or it won't be found in the choices.

**Comment by susanodd** [comment]
I'm working on this too, but by trying input.

I tried your input and it worked the first time.

Then I tried:

`{'en': [['hire'], ['bobblehead, lease']], 'nl': [['huren'], ['huren']]}`

But this gives an error with this line of code:

`elif field.name == 'semField':`

(Not the strip function)

**Comment by susanodd** [comment]
Not related, but in the "Antwoord" section of the XHR response from the signbank-test server, this variable is set:

`FILE_UPLOAD_TEMP_DIR 	None`

Maybe that is a problem?

**Comment by susanodd** [comment]
More information. Locally, I modified the code dusdanig that the actual "update" of the senses occurs.

This fails. It gives an error of constraint violation on the senses.

By the way, if I am missing a comma in the senses, it gives this feedback:

`    Senses: Sense input is not in the expected format. Try: '{"en":[["sense 1 keyword1", "sense 1 keyword2"],["sense 2 keyword1"]], "nl":[["sense 1 keyword1"],["sense 2 keyword1", "sense 2 keyword2"]]}'`

@Woseseltops that ought to be in the Swagger documentation.

**Comment by susanodd** [comment]
I am surprised that this bug hasn't happened before.

There are multiple "m2m_changed" Django functions called when the senses are updated.

The least painful way to mend this would be this, as suggested somewhere:

`my_object.relations.clear()`

to get rid of the old senses. Then use the same code as for Gloss Create Senses to add the new ones here.

**Comment by susanodd** [comment]
I made a pull request for the repair to the API gloss update, This allows the Senses field to be processed.

(But the code that processes the Senses does not work, as discussed above)

**Comment by susanodd** [comment]
@Woseseltops it's not clear to me how to add the following text to the Swagger file.

`    Senses: Sense input is not in the expected format. Try: '{"en":[["sense 1 keyword1", "sense 1 keyword2"],["sense 2 keyword1"]], "nl":[["sense 1 keyword1"],["sense 2 keyword1", "sense 2 keyword2"]]}'
`

This exact nested description needs to be added to Swagger. At the moment, Swagger merely writes "string" which is wrong.

Will you kindly add this?

**Comment by susanodd** [comment]
@Woseseltops please read the details above. They are lengthy but relevant.

**Comment by Woseseltops** [comment]
> [@Woseseltops](https://github.com/Woseseltops) it's not clear to me how to add the following text to the Swagger file.

You mean adding the exact format **within the string** to the OpenAPI specs (which Swagger just visualizes)? I don't think you can add so much detail there... I suggest to just explain it in the description.

However, perhaps more important: let's focus on the functionality first, and documenting it later. I'll assign this issue to you because I'm running out of time, while you seem to be halfway already.

**Comment by Woseseltops** [comment]
> But the question I have is "what" the API is actually doing.

Detect if the senses that come in are different from the current situation. If no, do nothing. If yes, update them (or recreate them, if that's easier for you).

**Comment by susanodd** [comment]
> > But the question I have is "what" the API is actually doing.
> 
> Detect if the senses that come in are different from the current situation. If no, do nothing. If yes, update them (or recreate them, if that's easier for you).

I was being cynical. That's why "what" is in parentheses.

Because the commas are a problem. So the "senses" could be identical, but not detectible as being identical, because of commas.

In the Signbank interface, you see the comma's. But they may or may not be separating keywords. It's ambiguous.

Like if we add a bunch of parentheses around things that are superfluous.

If the senses are created on Signbank in the interface, there can be commas inside the keyword (phrases). But they can't be there in the API input. This used to be documented in the examples.

The test that determines whether the "new senses" are identical to the "current senses" can fail. (Because of commas.) The comma separates in the API input but it can be included in the phrases inside Signbank.

I want to know if SignCollect is actually ALSO updating Senses. Or just echoing the senses back to Signbank.

**Comment by susanodd** [comment]
@rem0g can you please show your command again?

With the orginal one running the fixed code, it works fine.

It correctly detects that this is the same as the original senses:

`{"en": [["hire"], ["rent, lease"]], "nl": [["huren"], ["huren"]]}`

I'll deploy the fix on Monday.

Is your code actually trying to "update" the senses?

I have an old copy of the database and the senses you show match with what is in the database.

**Comment by susanodd** [comment]
> This is what was sent:
> 
> {'Senses': {'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}}
> 
> I have tried different variations with slashes around en/nl and arrays, but nothing is working so far.
> 
> [@Woseseltops](https://github.com/Woseseltops) I would be glad if you could fix this problem (OR explain in a clear way what formatting is expected with Senses) with alternative approach because this method is clearly not working for API purposes. :)

It needs double quotes not single quotes.

The right-hand side is a dictionary, not a string.

Also are you using the LANGUAGE_CODE "nl" ?

(The Senses field was supposed to be "Betekenissen" in Dutch. But it looks like the translation might be malfunctioning.)

**Comment by rem0g** [comment]
This is what was sent just recently: 

`{"Senses": {"en": "[[\"hire\"], [\"rent, lease\"]]", "nl": "[[\"huren\"], [\"huren\"]]"}}`

I am still getting 500 HTTP error. 

@susanodd if it was working with your script, can you elaborate how you have done it? Have you send the Senses update via url = "https://signbank.cls.ru.nl/dictionary/api_update_gloss/5/45834/" ?

I can imagine it will work while on local, but Senses update is being sent via that API. Please send me your code how you have done that. Thanks!



A bit extended 500 error codes:

```


results
{'glossid': '45834'}
/var/www/repo/signbank/gloss_update.py, line 119, in get_gloss_update_human_readable_value_dict
          

          
            


def get_gloss_update_human_readable_value_dict(request):
    post_data = json.loads(request.body.decode('utf-8'))

    value_dict = dict()
    for field in post_data.keys():
        value = post_data.get(field, '')


        value_dict[field] = value.strip()
                                 ^^^^^^^^^^^ …


    return value_dict


def check_fields_can_be_updated(value_dict, dataset, language_code):
    language_fields, api_fields_2024 = api_update_gloss_fields(dataset, language_code)
    errors = dict()



Local vars



Variable
Value




field
'Senses'


post_data
{'Senses': {'en': '[["hire"], ["rent, lease"]]',
            'nl': '[["huren"], ["huren"]]'}}


request
<WSGIRequest: POST '/dictionary/api_update_gloss/5/45834/'>


value
{'en': '[["hire"], ["rent, lease"]]', 'nl': '[["huren"], ["huren"]]'}


value_dict
{}
```

**Comment by susanodd** [comment]
The fix isn't live yet!!!

**Comment by susanodd** [comment]
This is incorrect:

```
{'Senses': {'en': '[["hire"], ["rent, lease"]]',
            'nl': '[["huren"], ["huren"]]'}}
```

There should not be quotes around this:

 `'[["hire"], ["rent, lease"]]'`

The length of the lists for each language are compared. It's a list.

**Comment by susanodd** [comment]
I just deployed and restarted signbank now.

**Comment by susanodd** [comment]
Please ignore what is in the Swagger description. It is misleading.

There used to be examples in a separate page in the Wiki. That page was deleted by @Woseseltops.
We can't get it back.

**Comment by rem0g** [comment]
Still not working, sorry. 

Please send me your code of how you update your Senses including the API connection to `api_update_gloss` :)

**Comment by susanodd** [comment]
There's some example code in the html temptates (used for debugging)

signbank/dictionary/templates/dictionary/

signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api.html
signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api_token_en.html
signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api_token_nl.html

The ones that say "token" in the filename you can open locally in the browser using "file://"

The one that doesn't say token, you can open in Signbank using

dictionary/test_am_update_gloss/5/49249/

(using the dataset ID and the gloss ID in the url. There is a template set up in views.py that just allows that to be processed.
Similar templates exist for other API testing.)

The first one:
signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api.html

you can set the interface language and the field names change language.

**Comment by susanodd** [comment]
@rem0g I should note that to actually UPDATE the senses, there is still a bug.

A new issue has been made for that #1461  (I'm working on that now, but I need help from @vanlummelhuizen for the signal that has a bug. When a sense is deleted, a signal is called that renumbers the remaining senses. But we don't want to do this, because the API is going to replace all the senses and create them again. The signal is where the bug is.)

The bug you found has to do with the "input" part of the request.

**Comment by rem0g** [comment]
Using https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api_token_en.html is giving me same HTTP 500 error with this input in the field senses:

{"en": [["hire"], ["rent, lease"]], "nl": [["huren"], ["huren"]]}

**Comment by susanodd** [comment]
Does it give any other information in the browser?

You are using it as file://......

**Comment by rem0g** [comment]
I have modified the console output as it produces HTTP 500 error in html code: 

`  <pre class="exception_value">&#x27;dict&#x27; object has no attribute &#x27;strip&#x27;</pre>
`

When using 

`{"en": [["hire"], ["rent, lease"]], "nl": [["huren"], ["huren"]]}
`

```
URL:         url : url + "/dictionary/api_update_gloss/" + datasetid + '/' + glossid + '/',
    var url = 'https://signbank.cls.ru.nl/';
    var datasetid = '5';
    var glossid = '45834';
```

Can you please post your script when you have managed to update your Senses via Python using requests.post Python module? I am curious to how you have managed to update it.

**Comment by rem0g** [comment]
This is mine: 

```
import requests
import json
from bs4 import BeautifulSoup
headers = {
    "Authorization": "Bearer xxxxx",
    'Content-Type': 'application/json',
    'Accept-Language': 'en',
}

url = "https://signbank.cls.ru.nl/dictionary/api_update_gloss/5/45834/"

senses_engels = [["hire"], ["rent, lease"]]
senses = [["huren"], ["huuuuren"]]

data = {}
data["Senses"] = {}
data["Senses"]["en"] = json.dumps(senses_engels)
data["Senses"]["nl"] = json.dumps(senses) 

print("Data to be sent:")
print(data)

# # Sending the data as raw JSON
response = requests.post(url, headers=headers, json=data)

print(f"Response Status Code: {response.status_code}")

if response.status_code == 200:
    try:
        # Parse JSON response
        json_response = response.json()
        print("JSON Response:")
        print(json.dumps(json_response, indent=4))
    except json.JSONDecodeError:
        print("Failed to decode JSON response.")
elif response.status_code == 500:
    # Save response.text to an HTML file
    with open("error_response.html", "w") as file:
        file.write(response.text)
    print("HTML error response saved to 'error_response.html'.")

    # Parse the HTML response with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find all <li> tags with class "frame user"
    li_elements = soup.find_all('li', class_='frame user')

    # Extract and print the content of the <li> elements
    print("Parsed <li> elements with class 'frame user':")
    for li in li_elements:
        text = li.get_text()
        if text.strip() != "":
            print(text.strip())
else:
    print(f"Unhandled status code: {response.status_code}")
    print("Response Text:")
    print(response.text)
```

**Comment by susanodd** [comment]
You are using solely Python and Javascript on your side?

I am relying on what is stored in the database, so making use of objects on the processing side.

It worked when the input senses was the same as what was already in the database. (So it did not need to actually update anything.)

However,
It's true there is a huge problem when you actually want to update the senses.

Unfortunately @Jetske isn't here anymore. She wrote the update senses code.

I need to rewrite it entirely since it isn't working at all now. (I'm working on it locally to get it to stop causing constraint violations.)

Unfortunately, neither @Woseseltops nor @vanlummelhuizen worked on the senses code.
@vanlummelhuizen assisted on the signals code. But that is also not the problem. (I removed the code that was causing that to fail. But it still can't create new senses. It keeps getting a constraint violation. I suspect there is some old object that needs to be removed but was not removed.)

**Comment by rem0g** [comment]
No I am using two different approaches to update Senses via Python (my script) or Javascript per script you provided. 

I would like to ask you to reproduce the problem for me and try to debug the function `get_gloss_update_human_readable_value_dict` as fast as possible. You can use my script I provided in my previous reply.

**Comment by susanodd** [comment]
I've got it working now!!

I just rewrote the code that updates the senses. The code is kind of sloppy at the moment.

I'll put in on the branch, then you can see it there. #1463

**Comment by vanlummelhuizen** [comment]
Did anyone carefully read what @Jetske wrote (which she didn't have to since she is not working for the RU anymore (I hope you had a nice vacation 🌞 ))? See https://github.com/Signbank/Global-signbank/issues/1360#issuecomment-2589572276

She says that, although not the best implementation, the dict with the senses should be send as a string:

{"Senses": "<a dict serialized as string>"} 

That dict-string is than later interpreted here:

https://github.com/Signbank/Global-signbank/blob/372ef1b3d9507e0b01cbccf0cbefcf207d0e50c3/signbank/gloss_update.py#L147-L170

The API docs are confusing. So, the code should probably be improved upon. But this could have been solved by reading things carefully, both code and relevant Github comments.

**Comment by susanodd** [comment]
It does not work when it's a string.

**Comment by vanlummelhuizen** [comment]
> It does not work when it's a string.

There is a bug, yes. But it is not because it is a string. It is this:

```diff
diff --git a/signbank/gloss_update.py b/signbank/gloss_update.py
index fc082ff7..1db25a31 100755
--- a/signbank/gloss_update.py
+++ b/signbank/gloss_update.py
@@ -478,7 +478,7 @@ def gloss_update_do_changes(user, gloss, changes, language_code):
                 original_senses = collect_revision_history_for_senses(gloss)
                 update_senses(gloss, new_value)
                 new_senses = collect_revision_history_for_senses(gloss)
-                changes_done.append((field.name, original_senses, new_senses))
+                changes_done.append((field, original_senses, new_senses))
             elif field.name == 'semField':
                 update_semantic_field(gloss, new_value, language_code)
                 changes_done.append((field.name, original_value, new_value))
```

My API test:

```bash
> curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <my-secret-key>" \
    -d "{\"Senses\": \"{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}\"}" \
    localhost:8001/dictionary/api_update_gloss/5/47662/
{"glossid": "47662", "errors": {}, "updatestatus": "Success"}
```

Note that `"{\"Senses\": \"{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}\"}"` in the command above is actually the JSON `{"Senses": "{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}"}`, where  `{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}` is in double quotes and therefore a string.

**Comment by susanodd** [comment]
> > It does not work when it's a string.
> 
> There is a bug, yes. But it is not because it is a string. It is this:
> 
> diff --git a/signbank/gloss_update.py b/signbank/gloss_update.py
> index fc082ff7..1db25a31 100755
> --- a/signbank/gloss_update.py
> +++ b/signbank/gloss_update.py
> @@ -478,7 +478,7 @@ def gloss_update_do_changes(user, gloss, changes, language_code):
>                  original_senses = collect_revision_history_for_senses(gloss)
>                  update_senses(gloss, new_value)
>                  new_senses = collect_revision_history_for_senses(gloss)
> -                changes_done.append((field.name, original_senses, new_senses))
> +                changes_done.append((field, original_senses, new_senses))
>              elif field.name == 'semField':
>                  update_semantic_field(gloss, new_value, language_code)
>                  changes_done.append((field.name, original_value, new_value))
> My API test:
> 
> > curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <my-secret-key>" \
>     -d "{\"Senses\": \"{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}\"}" \
>     localhost:8001/dictionary/api_update_gloss/5/47662/
> {"glossid": "47662", "errors": {}, "updatestatus": "Success"}
> Note that `"{\"Senses\": \"{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}\"}"` in the command above is actually the JSON `{"Senses": "{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}"}`, where `{'en': [['hire'], ['rent, lease']], 'nl': [['huren'], ['huren']]}` is in double quotes and therefore a string.

Yes, I already fixed that in the pull request.
The bug happened before that. During the "update_senses(gloss, new_value)"
It gives transaction management /consistency/unique constraint violated. That is the problem.

This did not used to happen because nobody was updating the senses. They have been using Batch Edit on Signbank.

**Comment by susanodd** [comment]
> Senses update doesnt work anymore again:
> 
> Payload:
> 
> ```
> 
> 
> {
>   "Senses": {
>     "en": [
>       [
>         "string"
>       ]
>     ],
>     "nl": [
>       [
>         "string"
>       ]
>     ]
>   }
> }
> ```
> 
> # AttributeError at /dictionary/api_update_gloss/5/47662/
> 'dict' object has no attribute 'strip'


@vanlummelhuizen this is the bug that reopened this issue. It's about a string. There was already a pull request and merge for the "parsing" part of the input.

But then another bug happened. If the senses field had changed from the stored senses, then the "update" caused constraint violations due to the transactions being duplicated. That was caused by the "reorder_senses" method that was being called in a signal.

**Comment by Woseseltops** [comment]
Okay, we have a quick solution (provided by @vanlummelhuizen ) and a larger solution (proposed by @susanodd) in PR #1463 . The quick solution is already live in production. I have tested both using the `curl` command suggested in this thread, in both cases providing the senses as string as indicated by Jetske.

Manual test results: 
* Quick solution (tested on the production server): the error goes away, but it only deletes existing senses without adding new ones.
* PR (tested on signbank-test): I'm seeing the senses as intended.

Seems like we need to review PR #1463 as quickly as possible; to be continued there.

**Comment by susanodd** [comment]
> Okay, we have a quick solution (provided by [@vanlummelhuizen](https://github.com/vanlummelhuizen) ) and a larger solution (proposed by [@susanodd](https://github.com/susanodd)) in PR [#1463](https://github.com/Signbank/Global-signbank/pull/1463) . The quick solution is already live in production. I have tested both using the `curl` command suggested in this thread, in both cases providing the senses as string as indicated by Jetske.
> 
> Manual test results:
> 
> * Quick solution (tested on the production server): the error goes away, but it only deletes existing senses without adding new ones.

URGENT disable updating senses in the API, before the API accidentally deletes senses
