### ISSUE TITLE
Error message when changing note type

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#569]
Both in Global and ASL Signbank

**Comment by Woseseltops** [comment]
Done. Turns out the update mechanism for note roles was still using an outdated way to retrieve the human value (which it sends back).

**Comment by ocrasborn** [comment]
Seems this still isn't working. In ASL SB, "About ID Gloss" (machine value 3) shows up as "ID Gloss Issue" in the interface.

**Comment by Woseseltops** [comment]
Hey @ocrasborn , the problem was not about error messages if you change the note type, but actually just a matter of reloading Signbank (which can only be done by me at the moment, #607 )
