### ISSUE TITLE
Not all text is translatable

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#703]
Quote from Jaime Burriel:

> I also found some pages that have fields not translated or hardocded, like "Available datasets page" table headers and the first line of the search fields tooltips: 'In many text fields, you can use patterns as follows:'

**Comment by vanlummelhuizen** [comment]
That should be easy to change because all occurrences of that text are in templates (see https://github.com/Signbank/Global-signbank/search?q=%22patterns+as+follows%22&type=code). Just make it a {% trans ... %} thing.

While you are (or I am) at it, perhaps also try to bring it down to one occurrence since they seem exact copies of each other.

**Comment by Woseseltops** [comment]
I think this nicely fits my 'add new interface language' branch for #696 !

**Comment by Woseseltops** [comment]
> While you are (or I am) at it, perhaps also try to bring it down to one occurrence since they seem exact copies of each other.

Orders executed.  They were not 100% identical, solved with a parameter.

**Comment by vanlummelhuizen** [comment]
Thank you. Dismissed ;)

**Comment by susanodd** [comment]
I'm looking to see what issues still need attending to.
This one hasn't been posted to for a while.
Related to this issue, there are some translation files that are apparently missing on lightning.
See the screenshots in #746. (Yes, it's about capitalisation, but while checking things I noticed some things were translated on my local server, but not on Global. Translations that used to show up.)
https://github.com/Signbank/Global-signbank/issues/746#issuecomment-1120913834

**Comment by susanodd** [comment]
There are quite a few of these non-trans texts in the Feedback section.

**Comment by susanodd** [comment]
@Woseseltops how extensive should the translations be, for example something like "Error" ?
Occasionally, there are some very long paragraphs.

**Comment by susanodd** [comment]
The Feedback text has been enclosed in trans directives.
This has been pushed to branch `title_caps`.
Additionally test for the existence of a previously uploaded video Feedback has been added.
This checks that the file also exists in the location:
 https://github.com/Signbank/Global-signbank/blob/cbfe53d2b452a88068a7649e6e436f70ed906228/signbank/settings/server_specific/default.py#L11

**Comment by susanodd** [comment]
I read through the wiki section on translation.
I have resolved most of the fuzzy text in the NL po file.
The four remaining are all "patterns" for plurals.

**Comment by Woseseltops** [comment]
> @Woseseltops how extensive should the translations be, for example something like "Error" ?

Can you give me an example of where you are in doubt, @susanodd ?

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/cbfe53d2b452a88068a7649e6e436f70ed906228/signbank/dictionary/templates/dictionary/import_media.html#L57

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/cbfe53d2b452a88068a7649e6e436f70ed906228/signbank/dictionary/views.py#L582-L583

**Comment by Woseseltops** [comment]
I would go for yes, make that translatable as well... Any arguments for why not do it? Just to be clear: it's not to up to us to actually provide the translation ;) .

**Comment by susanodd** [comment]
I left some things untranslated because they ended up "code" instead of string.
Others I modified the code to translate message texts using _( ) and using messages.
But this strategy didn't match well with accumulated lists of "feedback".

**Comment by susanodd** [comment]
The _( ) things can't be embedded in a list.
I probably need to create a template or resolve it in a different way.

**Comment by susanodd** [comment]
I'm busy working on this "other way to resolve". It's so annoying!

**Comment by susanodd** [comment]
I made a new template for `configure_handshapes` in order to resolve its translations!!

That leaves two functions for configuring that pass untranslated html as a response.
See confusion in #736 
https://github.com/Signbank/Global-signbank/issues/769#issuecomment-1132896117

**Comment by susanodd** [comment]
I've deleted some functions and their corresponding urls that are not being used anymore, rather than create templates for unused code in order to get translations.

https://github.com/Signbank/Global-signbank/blob/5a6317b04d92838886cd15ebbcf699e816147b73/signbank/dictionary/urls.py#L84
https://github.com/Signbank/Global-signbank/blob/5a6317b04d92838886cd15ebbcf699e816147b73/signbank/dictionary/urls.py#L96-L99

**Comment by susanodd** [comment]
I'm making significant improvements to the code in order to add translation to all of the error checking.
As part of the translation, many of the guards have been improved to include elegant rendering to the warning.html template, with the translated error message, rather than just clumsy Http404. 
(Inspired by the code review of @Woseseltops for expiry datum.)

**Comment by susanodd** [comment]
The last one above I pushed to master since it's only the .po file for Dutch.

**Comment by susanodd** [comment]
One thing that hasn't been resolved is the `bootstrap3_title` texts in the templates. (The browser window headers.)

**Comment by susanodd** [comment]
The web page titles are now translatable. This has been pushed to branch `title_caps`.

**Comment by susanodd** [comment]
In modifying the bootstrap title headings to be translated, one page remains, unused_videos.html
The python behind this template has some bugs in it and I'm fixing this.

**Comment by susanodd** [comment]
I forgot to include this screenshot above. This is for get_unused_videos. I revised it to be a table, and it includes translations for the text now.

![get_unused_videos_display](https://user-images.githubusercontent.com/24272544/171151594-ed490d68-c41c-456c-bc74-5a9928fca07a.png)

**Comment by susanodd** [comment]
I followed the instructions in the wiki to makemessages for NL.
Yykes! There are 246 fuzzy translations!!!

**Comment by susanodd** [comment]
Baah. This is too hilarious. Look at what Django automatically does:

`#: signbank/dictionary/templates/dictionary/admin_lemma_list.html:111`
`#, fuzzy`
`#| msgid "Search morpheme"`
`msgid "Search Lemma"`
`msgstr "Zoek morfeem"`

**Comment by susanodd** [comment]
I repaired all the fuzzy translations and otherwise prepared the newly generated 'po' file for NL.
It compiles okay and provides (NL) translation strings for all the newly translated texts in this issue / branch.

**Comment by susanodd** [comment]
These are live now!!

**Comment by susanodd** [comment]
Some text has been made translatable in the pull request #870.

**Comment by susanodd** [comment]
Pointed out by @Woseseltops in the code review of  #870:
 
`$(e).html("{% blocktrans %}Hide empty frequencies{% endblocktrans %}");`

**Comment by susanodd** [comment]
> Pointed out by @Woseseltops in the code review of #870:
> 
> `$(e).html("{% blocktrans %}Hide empty frequencies{% endblocktrans %}");`

I did this!

**Comment by susanodd** [comment]
I compiled the messages a few days ago for the new server. (This had not been done!)

I generated new messages to add the new texts but only for NL

This ought to be done for the other languages, but as far as I know, people are working on translations using the old (current) versions of the .po files. It's best if the files with the translations being worked on are put online, before generating more phrases to translate.

**Comment by susanodd** [comment]
This is more or less complete. When we come across things, we add translation.

However, the translators don't seem to edit the .po files. Some of these have not been re-generated as it's not clear if the translators have supplied new .po files based on filling in old .po files.
